parallel::detectCores()
options(Ncpus = 4)

install.packages("arrow")
install.packages("assertthat")
install.packages("devtools")
install.packages("dplyr")
install.packages("dbplyr")
install.packages("duckdb")
install.packages("ggplot2")
install.packages("haven")
install.packages("knitr")
install.packages("mapsf")
install.packages("MTA")
install.packages("readxl")
install.packages("remotes")
install.packages("roxygen2")
install.packages("rmapshaper")
install.packages("rmarkdown")
install.packages("sf")
install.packages("spdep")
install.packages("tinytex")


install.packages("mapinsetr", repos = "https://riatelab.r-universe.dev")
